name: Simulator tests
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fastlane:
    runs-on: namespace-profile-macos-default
    steps:
      - uses: actions/checkout@v4
      - uses: Wandalen/wretry.action@master
        with: # iOS tests are flaky for no good reason
          command: |
            fastlane screenshots
          attempt_limit: 5
          attempt_delay: 30000

  test:
    strategy:
      matrix:
        a: [0, 1, 2, 3, 4, 5, 6, 7]
        b: [0, 1, 2, 3, 4, 5, 6, 7]
    runs-on: namespace-profile-macos-default
    steps:
      - uses: actions/checkout@v4
      - uses: Wandalen/wretry.action@master
        with:
          command: |
            xcodebuild test -scheme ios-demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -quiet
