name: Simulator tests
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fastlane:
    runs-on: namespace-profile-qonto-demo
    steps:
      - uses: actions/checkout@v4
      - uses: Wandalen/wretry.action@master
        with:
          command: |
            fastlane screenshots
          attempt_limit: 5
          attempt_delay: 30000

  test:
    runs-on: namespace-profile-qonto-demo
    steps:
      - uses: actions/checkout@v4
      - uses: Wandalen/wretry.action@master
        with:
          command: |
            xcodebuild test -scheme ios-demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -quiet
